services:
  db-keycloak:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - badgehub_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    ports:
      - "8080:8080"
    env_file:
      - .env
    entrypoint: sh -c "/opt/keycloak/bin/kc.sh start"
    environment:
      - KC_PROXY=edge
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_DB_SCHEMA=public
      - KC_DB_USERNAME=keycloak
      - KC_DB_URL_HOST=db-keycloak
      - KC_DB_URL_DATABASE=keycloak
      - KC_LOG_LEVEL=WARN
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY=true
    command:
      - start
    volumes:
      - ./auth/import:/opt/keycloak/data/import
    depends_on:
      - db-keycloak
    networks:
      - badgehub_network

networks:
  badgehub_network:
    name: badgehub_network

volumes:
  postgres_data:
